### ISSUE TITLE
Link to pad is not on the correct domain

### ISSUE THREAD

**Issue by meepmeep** [HarryBleckert/ep_adminpads3#3]
On the admin's pad list, link to the pad are "https://moodle.ash-berlin.eu/mod/etherpadlite/view.php?pad=[PAD_NAME]" instead of https://[my-etherpad.tld]/"

**Comment by HarryBleckert** [comment]
Thx for reminding me.
Soon as I have the time, I'll change the link.

**Comment by HarryBleckert** [comment]
URL has been set back to default
